server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Toute route inconnue → renvoyée vers index.html (React Router gère le reste)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
