"""ajout duree_minutes dans eleve_classe

Revision ID: 3629f22ea3a2
Revises: 622b883d1969
Create Date: 2026-06-10 12:14:14.256879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3629f22ea3a2'
down_revision = '622b883d1969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve_classe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve_classe', schema=None) as batch_op:
        batch_op.drop_column('duree_minutes')

    # ### end Alembic commands ###
