"""ajoute date_creneau aux creneaux perso

Revision ID: 424a00f2018a
Revises: 83833e71e14d
Create Date: 2026-06-26 09:42:09.235414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424a00f2018a'
down_revision = '83833e71e14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creneaux_perso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creneau', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creneaux_perso', schema=None) as batch_op:
        batch_op.drop_column('date_creneau')

    # ### end Alembic commands ###
