"""ajout date_debut, date_fin et table creneaux_perso

Revision ID: 622b883d1969
Revises: df62b500993c
Create Date: 2026-06-08 15:16:23.500194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622b883d1969'
down_revision = 'df62b500993c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creneaux_perso',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jour', sa.String(length=50), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creneaux', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_debut', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creneaux', schema=None) as batch_op:
        batch_op.drop_column('date_fin')
        batch_op.drop_column('date_debut')

    op.drop_table('creneaux_perso')
    # ### end Alembic commands ###
