"""ajoute date_cours aux objectifs

Revision ID: 83833e71e14d
Revises: 987f64df9aab
Create Date: 2026-06-25 16:56:19.131229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83833e71e14d'
down_revision = '987f64df9aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_cours', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objectifs', schema=None) as batch_op:
        batch_op.drop_column('date_cours')

    # ### end Alembic commands ###
