"""ajout semaine_alternance dans creneau

Revision ID: 987f64df9aab
Revises: e2ab2c0cf397
Create Date: 2026-06-11 12:12:03.166598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987f64df9aab'
down_revision = 'e2ab2c0cf397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creneaux', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semaine_alternance', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creneaux', schema=None) as batch_op:
        batch_op.drop_column('semaine_alternance')

    # ### end Alembic commands ###
