"""création des tables

Revision ID: df62b500993c
Revises: 
Create Date: 2026-06-02 15:17:09.934087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df62b500993c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_fcm', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eleves',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('notifications',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professeurs',
    sa.Column('utilisateur_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('utilisateur_id')
    )
    op.create_table('classes',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('jours_horaires', sa.JSON(), nullable=False),
    sa.Column('nombre_propositions', sa.Integer(), nullable=False),
    sa.Column('nombre_voeux_requis', sa.Integer(), nullable=False),
    sa.Column('nombre_jours_min', sa.Integer(), nullable=False),
    sa.Column('code_classe', sa.String(length=8), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_classe')
    )
    op.create_table('evenements',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('destinataires', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eleve_classe',
    sa.Column('eleve_id', sa.String(length=36), nullable=True),
    sa.Column('classe_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.utilisateur_id'], )
    )
    op.create_table('eleve_evenement',
    sa.Column('eleve_id', sa.String(length=36), nullable=True),
    sa.Column('evenement_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], )
    )
    op.create_table('plannings',
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('numero_proposition', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('valide_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voeux',
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('creneaux_souhaites', sa.JSON(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('soumis_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creneaux',
    sa.Column('planning_id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('classe_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('jour', sa.String(length=50), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['planning_id'], ['plannings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectifs',
    sa.Column('professeur_id', sa.String(length=36), nullable=False),
    sa.Column('eleve_id', sa.String(length=36), nullable=False),
    sa.Column('creneau_id', sa.String(length=36), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('conseils', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('modifie_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creneau_id'], ['creneaux.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.utilisateur_id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['professeurs.utilisateur_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objectifs')
    op.drop_table('creneaux')
    op.drop_table('voeux')
    op.drop_table('plannings')
    op.drop_table('eleve_evenement')
    op.drop_table('eleve_classe')
    op.drop_table('evenements')
    op.drop_table('classes')
    op.drop_table('professeurs')
    op.drop_table('notifications')
    op.drop_table('eleves')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
