"""ajout couleur dans classe et parametres dans utilisateur

Revision ID: e2ab2c0cf397
Revises: 3629f22ea3a2
Create Date: 2026-06-10 18:28:42.013214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ab2c0cf397'
down_revision = '3629f22ea3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('couleur', sa.String(length=7), nullable=True))

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametres', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_column('parametres')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('couleur')

    # ### end Alembic commands ###
